### ISSUE TITLE
怎么使用 chatbi-UI？

### ISSUE THREAD

**Issue by comeonzhj** [chatbi/chatbi#2]
两个项目都 Clone 了，但是怎么把他们关联起来呢？

直接运行 Chatbi 页面只显示 Hello World……

**Comment by yugasun** [comment]
已更新项目说明，参考最新 [README](https://github.com/chatbi/chatbi/blob/main/README.md) 运行就可以了。

**Comment by yugasun** [comment]
已更新项目说明，参考最新 [README](https://github.com/chatbi/chatbi/blob/main/README.md) 运行就可以了。
