### ISSUE TITLE
ERR_NETWORK

### ISSUE THREAD

**Issue by woodiewu** [chatbi/chatbi#3]
按照readme安装好后，输入query报网络问题。
<img width="1796" alt="image" src="https://github.com/chatbi/chatbi/assets/27182806/b6dc8256-9ecb-4953-ae77-3824678f67f7">

**Comment by yugasun** [comment]
确认下后端服务是否启动？

**Comment by woodiewu** [comment]
> 确认下后端服务是否启动？

已解决，修改了配置文件的ip得以解决
