### ISSUE TITLE
 ERROR [ChatService] TypeError: fetch failed

### ISSUE THREAD

**Issue by KEAI404** [chatbi/chatbi#4]
![image](https://github.com/chatbi/chatbi/assets/61661395/e5f8efe7-25dc-44f7-8e39-4258f7df6b84)
![image](https://github.com/chatbi/chatbi/assets/61661395/4a8b6ca7-76a8-4373-b587-3fea2a7db744)
点击运行报错，不知道怎么解决。

**Comment by yugasun** [comment]
看起来是 GPT api 服务异常，可以换一个稳定点的 GPT 服务试试
